#ðŸ“Œ ExtracciÃ³n

In [358]:
import pandas as pd

In [359]:
datos= pd.read_json('/content/TelecomX_Data.json')
datos

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

In [360]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

In [361]:
datos.dtypes

customerID    object
Churn         object
customer      object
phone         object
internet      object
account       object
dtype: object

#ðŸ”§ TransformaciÃ³n

In [362]:

# Usamos json_normalize para expandir los diccionarios
df_normalizado = pd.concat([
    datos[['customerID', 'Churn']],
    pd.json_normalize(datos['customer']),
    pd.json_normalize(datos['phone']),
    pd.json_normalize(datos['internet']),
    pd.json_normalize(datos['account'])
], axis=1)

# Mostrar las primeras filas
df_normalizado.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [363]:
df_normalizado.shape

(7267, 21)

In [364]:
##Para saber si tengo valores ausentes o faltantes
df_normalizado.isnull().values.any()

np.False_

In [365]:
#Â¿cuÃ¡ntos valores ausentes hay por columna?
df_normalizado.isnull().sum()
##Veo que Charges.Total tiene 11 valores ausentes o vacÃ­os.

customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
Charges.Monthly     0
Charges.Total       0
dtype: int64

In [366]:
#Â¿CuÃ¡ntos valores duplicados tengo?
df_normalizado.duplicated().sum()
#No tengo :)

np.int64(0)

In [367]:
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [368]:
import numpy as np

In [369]:

# Reemplazamos espacios en vacÃ­os y strings vacÃ­os por NaN
#df_normalizado = df_normalizado.replace(r'^\s*$', np.nan, regex=True)

In [370]:
df_normalizado.head(5)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [371]:
##Cambio el objeto de Charges.Total por un float64

# Reemplazamos strings o espacios con NaN
df_normalizado['Charges.Total'] = df_normalizado['Charges.Total'].replace(r'^\s*$', np.nan, regex=True)

In [372]:
# Convertimos la columna a tipo float64
df_normalizado['Charges.Total'] = df_normalizado['Charges.Total'].astype(np.float64)

In [373]:
##Cambio gender por string
df_normalizado['gender'] = df_normalizado['gender'].str.lower().astype('string')

In [374]:
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   string
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7256 non-null   float64
dtypes: float64(2), int64(2), object(16), string(1)
memory usage: 1.2+ MB

In [375]:
# Ver los valores Ãºnicos de cada columna
df_normalizado.apply(pd.Series.unique)

customerID          [0002-ORFBO, 0003-MKNFE, 0004-TLHLJ, 0011-IGKF...
Churn                                                     [No, Yes, ]
gender                                                 [female, male]
SeniorCitizen                                                  [0, 1]
Partner                                                     [Yes, No]
Dependents                                                  [Yes, No]
tenure              [9, 4, 13, 3, 71, 63, 7, 65, 54, 72, 5, 56, 34...
PhoneService                                                [Yes, No]
MultipleLines                             [No, Yes, No phone service]
InternetService                                [DSL, Fiber optic, No]
OnlineSecurity                         [No, Yes, No internet service]
OnlineBackup                           [Yes, No, No internet service]
DeviceProtection                       [No, Yes, No internet service]
TechSupport                            [Yes, No, No internet service]
StreamingTV                            [Yes, No, No internet service]
StreamingMovies                        [No, Yes, No internet service]
Contract                         [One year, Month-to-month, Two year]
PaperlessBilling                                            [Yes, No]
PaymentMethod       [Mailed check, Electronic check, Credit card (...
Charges.Monthly     [65.6, 59.9, 73.9, 98.0, 83.9, 69.4, 109.7, 84...
Charges.Total       [593.3, 542.4, 280.85, 1237.85, 267.4, 571.45,...
dtype: object

In [376]:
##Cambio de nombre a las columnas
# quitar puntos, espacios y poner todo en minÃºsculas
df_normalizado.columns = df_normalizado.columns.str.replace('.', '', regex=False).str.replace(' ', '').str.lower()
df_normalizado

,customerid,churn,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,...,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,chargesmonthly,chargestotal
0,0002-ORFBO,No,female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30
1,0003-MKNFE,No,male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40
2,0004-TLHLJ,Yes,male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7263,9992-RRAMN,Yes,male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7264,9992-UJOEL,No,male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60

In [377]:
df_normalizado['paymentmethod'].head(10)

0                 Mailed check
1                 Mailed check
2             Electronic check
3             Electronic check
4                 Mailed check
5      Credit card (automatic)
6    Bank transfer (automatic)
7      Credit card (automatic)
8             Electronic check
9                 Mailed check
Name: paymentmethod, dtype: object

In [378]:
df_normalizado['paymentmethod'].unique()

array(['Mailed check', 'Electronic check', 'Credit card (automatic)',
       'Bank transfer (automatic)'], dtype=object)

In [379]:
#ReemplazarÃ© los Nan de la columna de chargestotal por 0
df_normalizado['chargestotal'].fillna(0, inplace=True)

/tmp/ipython-input-1921064591.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_normalizado['chargestotal'].fillna(0, inplace=True)

In [380]:
#Â¿cuÃ¡ntos valores ausentes hay por columna?
df_normalizado.isnull().sum()
##Y veo que ya no tengo valores ausentes o faltantes

customerid          0
churn               0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
chargesmonthly      0
chargestotal        0
dtype: int64

In [381]:
##Ahora me gustarÃ­a cambiar las columnas de

In [382]:
df_normalizado.dtypes

customerid                  object
churn                       object
gender              string[python]
seniorcitizen                int64
partner                     object
dependents                  object
tenure                       int64
phoneservice                object
multiplelines               object
internetservice             object
onlinesecurity              object
onlinebackup                object
deviceprotection            object
techsupport                 object
streamingtv                 object
streamingmovies             object
contract                    object
paperlessbilling            object
paymentmethod               object
chargesmonthly             float64
chargestotal               float64
dtype: object

In [383]:
##Ahora hago una lista con las columnas a las cuales me gustarÃ­a cambiarles los valores de Yes, No y Sin servicios por
##0 para No, 1 para Yes y 2 para Sin servicios
columns_yesno = ['churn','onlinesecurity', 'partner', 'dependents','phoneservice', 'multiplelines', 'onlinebackup', 'deviceprotection', 'techsupport','streamingtv','streamingmovies', 'paperlessbilling']

In [384]:
for col in columns_yesno:
    print(f"\nColumna: {col}")
    print(df_normalizado[col].unique())

Columna: churn
['No' 'Yes' '']

Columna: onlinesecurity
['No' 'Yes' 'No internet service']

Columna: partner
['Yes' 'No']

Columna: dependents
['Yes' 'No']

Columna: phoneservice
['Yes' 'No']

Columna: multiplelines
['No' 'Yes' 'No phone service']

Columna: onlinebackup
['Yes' 'No' 'No internet service']

Columna: deviceprotection
['No' 'Yes' 'No internet service']

Columna: techsupport
['Yes' 'No' 'No internet service']

Columna: streamingtv
['Yes' 'No' 'No internet service']

Columna: streamingmovies
['No' 'Yes' 'No internet service']

Columna: paperlessbilling
['Yes' 'No']

In [385]:
##Eliminar espacios vacios o strings en mi lista de columnas columns_yesno
for col in columns_yesno:
    df_normalizado[col] = df_normalizado[col].astype(str).str.strip().str.lower()

In [386]:
def convertir_yesno(valor):
    if str(valor).strip().lower() == 'no':
        return 0
    elif str(valor).strip().lower() == 'yes':
        return 1
    else:
        return 2

# Aplicar la funciÃ³n a cada columna de la lista
for col in columns_yesno:
    df_normalizado[col] = df_normalizado[col].apply(convertir_yesno)

In [387]:
for col in columns_yesno:
    print(f"\nValores distintos de 'yes' o 'no' en la columna '{col}':")
    print(df_normalizado[df_normalizado[col] == 2][col].value_counts())

Valores distintos de 'yes' o 'no' en la columna 'churn':
churn
2    224
Name: count, dtype: int64

Valores distintos de 'yes' o 'no' en la columna 'onlinesecurity':
onlinesecurity
2    1581
Name: count, dtype: int64

Valores distintos de 'yes' o 'no' en la columna 'partner':
Series([], Name: count, dtype: int64)

Valores distintos de 'yes' o 'no' en la columna 'dependents':
Series([], Name: count, dtype: int64)

Valores distintos de 'yes' o 'no' en la columna 'phoneservice':
Series([], Name: count, dtype: int64)

Valores distintos de 'yes' o 'no' en la columna 'multiplelines':
multiplelines
2    707
Name: count, dtype: int64

Valores distintos de 'yes' o 'no' en la columna 'onlinebackup':
onlinebackup
2    1581
Name: count, dtype: int64

Valores distintos de 'yes' o 'no' en la columna 'deviceprotection':
deviceprotection
2    1581
Name: count, dtype: int64

Valores distintos de 'yes' o 'no' en la columna 'techsupport':
techsupport
2    1581
Name: count, dtype: int64

Valores distintos de 'yes' o 'no' en la columna 'streamingtv':
streamingtv
2    1581
Name: count, dtype: int64

Valores distintos de 'yes' o 'no' en la columna 'streamingmovies':
streamingmovies
2    1581
Name: count, dtype: int64

Valores distintos de 'yes' o 'no' en la columna 'paperlessbilling':
Series([], Name: count, dtype: int64)

In [388]:
df_normalizado

,customerid,churn,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,...,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,chargesmonthly,chargestotal
0,0002-ORFBO,0,female,0,1,1,9,1,0,DSL,...,1,0,1,1,0,One year,1,Mailed check,65.60,593.30
1,0003-MKNFE,0,male,0,0,0,9,1,1,DSL,...,0,0,0,0,1,Month-to-month,0,Mailed check,59.90,542.40
2,0004-TLHLJ,1,male,0,0,0,4,1,0,Fiber optic,...,0,1,0,0,0,Month-to-month,1,Electronic check,73.90,280.85
3,0011-IGKFF,1,male,1,1,0,13,1,0,Fiber optic,...,1,1,0,1,1,Month-to-month,1,Electronic check,98.00,1237.85
4,0013-EXCHZ,1,female,1,1,0,3,1,0,Fiber optic,...,0,0,1,1,0,Month-to-month,1,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,0,female,0,0,0,13,1,0,DSL,...,0,0,1,0,0,One year,0,Mailed check,55.15,742.90
7263,9992-RRAMN,1,male,0,1,0,22,1,1,Fiber optic,...,0,0,0,0,1,Month-to-month,1,Electronic check,85.10,1873.70
7264,9992-UJOEL,0,male,0,0,0,2,1,0,DSL,...,1,0,0,0,0,Month-to-month,1,Mailed check,50.30,92.75
7265,9993-LHIEB,0,male,0,1,1,67,1,0,DSL,...,0,1,1,0,1,Two year,0,Mailed check,67.85,4627.65
7266,9995-HOTOH,0,male,0,1,1,63,0,2,DSL,...,1,1,0,1,1,Two year,0,Electronic check,59.00,3707.60

In [389]:
df_normalizado.dtypes

customerid                  object
churn                        int64
gender              string[python]
seniorcitizen                int64
partner                      int64
dependents                   int64
tenure                       int64
phoneservice                 int64
multiplelines                int64
internetservice             object
onlinesecurity               int64
onlinebackup                 int64
deviceprotection             int64
techsupport                  int64
streamingtv                  int64
streamingmovies              int64
contract                    object
paperlessbilling             int64
paymentmethod               object
chargesmonthly             float64
chargestotal               float64
dtype: object

In [392]:
# Crear la columna Cuentas_Diarias como mensual / 30
df_normalizado['cuentasdiarias'] = df_normalizado['chargesmonthly'] / 30

In [393]:
df_normalizado.head(5)

,customerid,churn,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,chargesmonthly,chargestotal,cuentasdiarias
0,0002-ORFBO,0,female,0,1,1,9,1,0,DSL,...,0,1,1,0,One year,1,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,0,male,0,0,0,9,1,1,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,1,male,0,0,0,4,1,0,Fiber optic,...,1,0,0,0,Month-to-month,1,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,1,male,1,1,0,13,1,0,Fiber optic,...,1,0,1,1,Month-to-month,1,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,1,female,1,1,0,3,1,0,Fiber optic,...,0,1,1,0,Month-to-month,1,Mailed check,83.9,267.40,2.796667

In [394]:
df_normalizado.dtypes

customerid                  object
churn                        int64
gender              string[python]
seniorcitizen                int64
partner                      int64
dependents                   int64
tenure                       int64
phoneservice                 int64
multiplelines                int64
internetservice             object
onlinesecurity               int64
onlinebackup                 int64
deviceprotection             int64
techsupport                  int64
streamingtv                  int64
streamingmovies              int64
contract                    object
paperlessbilling             int64
paymentmethod               object
chargesmonthly             float64
chargestotal               float64
cuentasdiarias             float64
dtype: object

In [395]:
##Guardar mi df en archivo csv
df_normalizado.to_csv('df_clean_Telecom.csv')

#ðŸ“Š Carga y anÃ¡lisis

#ðŸ“„Informe final